@startuml
title Controlador de Semáforo con Detector de Emergencia y Peatones

hide empty description
skinparam state {
  BackgroundColor #eef7ff
  BorderColor #22577A
  StartColor #38A3A5
}

[*] --> VERDE_A : nreset='0'

state VERDE_A
state AMARILLO_A
state VERDE_B
state AMARILLO_B
state EMERGENCIA_A
state EMERGENCIA_B
state VERDE_ADICIONAL_A
state VERDE_ADICIONAL_B
state CANCELA_A 
state CANCELA_B

' -------- Región A --------
VERDE_A --> EMERGENCIA_A : (solicitud_emergencia_a) and (t_out)
VERDE_A --> AMARILLO_A     : (timer_t_out) and (not solicitud_peaton_a) and (not solicitud_emergencia_a)
VERDE_A --> CANCELA_A      : (solicitud_emergencia_b) and (not solicitud_peaton_a) and (not solicitud_emergencia_a)
VERDE_A --> VERDE_ADICIONAL_A: (solicitud_peaton_a) and (t_out)

AMARILLO_A --> VERDE_B     : t_out

EMERGENCIA_A --> AMARILLO_A : not solicitud_emergencia_a

' -------- Región B --------
VERDE_B --> EMERGENCIA_B : (solicitud_emergencia_b) and (t_out)
VERDE_B --> AMARILLO_B     : (timer_t_out) and (not solicitud_peaton_b) and (not solicitud_emergencia_b)
VERDE_B --> CANCELA_B      : (solicitud_emergencia_a) and (not solicitud_peaton_b) and (not solicitud_emergencia_b)
VERDE_B --> VERDE_ADICIONAL_B: (solicitud_peaton_b) and (t_out)

AMARILLO_B --> VERDE_A     : t_out

EMERGENCIA_B --> AMARILLO_B : not solicitud_emergencia_b

@enduml
